# Generated by Django 5.2.17 on 2026-08-06 15:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='categoría')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('like_new', 'Como nuevo'), ('good', 'Buen estado'), ('fair', 'Aceptable'), ('poor', 'Mal estado')], default='good', max_length=20, verbose_name='estado')),
                ('usage_frequency', models.CharField(choices=[('daily', 'A diario'), ('weekly', 'Cada semana'), ('monthly', 'Cada mes'), ('rarely', 'Rara vez'), ('never', 'Nunca')], default='rarely', max_length=20, verbose_name='frecuencia de uso')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='fecha de compra')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio de compra')),
                ('last_used_at', models.DateField(blank=True, null=True, verbose_name='último uso')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'objeto',
                'verbose_name_plural': 'objetos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('url', models.URLField(blank=True, verbose_name='enlace')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio actual')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio objetivo')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='categoría')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('waiting', 'En espera'), ('comparing', 'Comparando'), ('possible_purchase', 'Compra posible'), ('purchased', 'Comprado'), ('discarded', 'Descartado')], default='waiting', max_length=30, verbose_name='estado')),
                ('waiting_days', models.PositiveIntegerField(default=7, verbose_name='días de espera')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='fecha de revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='comprado')),
                ('discarded_at', models.DateTimeField(blank=True, null=True, verbose_name='descartado')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='wishlist.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'precio',
                'verbose_name_plural': 'precios',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='necesidad')),
                ('value_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='valor')),
                ('interest_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='interés')),
                ('expected_uses', models.PositiveIntegerField(default=0, verbose_name='usos esperados')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='respuestas')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='wishlist.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'revisión',
                'verbose_name_plural': 'revisiones',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('url', models.URLField(blank=True, verbose_name='enlace')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio')),
                ('similarity_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='similitud')),
                ('quality_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='calidad')),
                ('durability_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='durabilidad')),
                ('warranty_months', models.PositiveIntegerField(default=0, verbose_name='garantía (meses)')),
                ('is_second_hand', models.BooleanField(default=False, verbose_name='segunda mano')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='wishlist.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'alternativa',
                'verbose_name_plural': 'alternativas',
                'ordering': ['price', 'created_at'],
            },
        ),
    ]
