# Generated by Django 5.2.17 on 2026-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_possible_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('waiting', 'En espera'), ('comparing', 'Comparando'), ('purchased', 'Comprado'), ('discarded', 'Descartado')], default='waiting', max_length=30, verbose_name='estado'),
        ),
    ]
