# Generated by Django 5.2.17 on 2026-08-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionreview',
            name='value_score',
        ),
    ]
