# Generated by Django 5.2.17 on 2026-08-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_remove_decisionreview_value_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionreview',
            name='expected_uses',
        ),
    ]
