# Generated by Django 5.2.17 on 2026-08-07 10:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_remove_decisionreview_expected_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_tier_1', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Umbral de precio bajo (€)')),
                ('waiting_days_1', models.PositiveSmallIntegerField(default=7, verbose_name='Días de espera para precios bajos')),
                ('price_tier_2', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Umbral de precio medio (€)')),
                ('waiting_days_2', models.PositiveSmallIntegerField(default=15, verbose_name='Días de espera para precios medios')),
                ('price_tier_3', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Umbral de precio alto (€)')),
                ('waiting_days_3', models.PositiveSmallIntegerField(default=30, verbose_name='Días de espera para precios altos')),
                ('waiting_days_max', models.PositiveSmallIntegerField(default=45, verbose_name='Días de espera para precios muy altos')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuración',
            },
        ),
    ]
