# Generated by Django 5.2.17 on 2026-08-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_appsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owneditem',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='owneditem',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='owneditem',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='owneditem',
            name='usage_frequency',
        ),
        migrations.AddField(
            model_name='owneditem',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL de imagen'),
        ),
        migrations.AddField(
            model_name='owneditem',
            name='url',
            field=models.URLField(blank=True, verbose_name='web de compra'),
        ),
    ]
