# Generated by Django 5.2.17 on 2026-08-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_remove_owneditem_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneditem',
            name='replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_replacements', to='wishlist.product', verbose_name='siguiente compra'),
        ),
    ]
