# Generated by Django 5.2.17 on 2026-08-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_owneditem_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneditem',
            name='buy_again',
            field=models.BooleanField(default=False, verbose_name='comprar de nuevo'),
        ),
    ]
